image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-python.python

tasks:
  - init: |
      psql -c "CREATE USER lightning WITH PASSWORD 'test';"
      psql -c "CREATE DATABASE lightning OWNER lightning;"
      poetry export -f requirements.txt -o requirements.txt --without-hashes --dev
      pip3 install -r requirements.txt