stages:
  - Static Code Analysis
  - Publish

flake8:
  stage: Static Code Analysis
  image: python:3.8-buster
  script:
  - pip install flake8
  - flake8 .
  only:
    changes:
      - lightning/**/*

isort:
  stage: Static Code Analysis
  image: python:3.8-buster
  script:
    - pip install isort
    - isort --check --diff .
  only:
    changes:
      - "**/*.py"

variables:
  POSTGRES_DB: lightningbot
  POSTGRES_USER: lightningbot
  POSTGRES_PASSWORD: "test"

Test Schema Creation:
  stage: Static Code Analysis
  image: postgres
  services:
  - postgres
  script:
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v "ON_ERROR_STOP=1" -f scripts/schema.sql
  only:
    changes:
      - scripts/*.{sql}

Publish release to Sentry:
  stage: Publish
  image: getsentry/sentry-cli
  variables:
    GIT_STRATEGY: "clone"
    GIT_DEPTH: 0
  script:
    - echo "Create a new release for $CI_COMMIT_SHA"
    - sentry-cli releases new $CI_COMMIT_SHA --project $SENTRY_PROJECT
    - sentry-cli releases set-commits --auto "$CI_COMMIT_SHA"
    - sentry-cli releases finalize $CI_COMMIT_SHA
    - echo "Finalized release for $CI_COMMIT_SHA"

