image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      psql -c "CREATE USER lightning WITH PASSWORD 'test';"
      psql -c "CREATE DATABASE lightning OWNER lightning;"
      poetry export -o requirements.txt --without-hashes --dev && pip3 install -r requirements.txt
    command: python3 -m lightning
