[tool.poetry]
name = "Lightning.py"
version = "3.0.0-alpha"
description = ""
authors = ["LightSage <lightsage01@gmail.com>"]
license = "AGPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
"discord.py" = {git = "https://github.com/LightSage/discord.py"}
Pillow = "^7.2.0"
python-dateutil = "^2.8.1"
jishaku = "^1.19.0"
parsedatetime = "^2.6"
toml = "^0.10.1"
psutil = "^5.7.2"
tabulate = "^0.8.7"
uwuify = "^1.0.1"
hiredis = "^1.1.0"
aredis = "^1.1.8"
feedparser = "^5.2.1"
asyncpg = "^0.21.0"
uvloop = "^0.14.0"
fuzzywuzzy = {extras = ["speedup"], version = "^0.18.0"}
discord-ext-menus = {git = "https://github.com/LightSage/discord-ext-menus"}
discord-flags = "^2.1.1"
lru_dict = "^1.1.6"
sentry-sdk = "0.16.5"
migra = {extras = ["pg"], version = "^1.0.1597915807", optional = true}

[tool.poetry.dev-dependencies]
isort = "^5.4.2"
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
