name: 'Test Migrations'

on:
  push: {}
  workflow_dispatch: {}

jobs:
  test:
    services:
        postgres:
          image: postgres:16
          env:
            POSTGRES_USERNAME: lightning
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: lightning
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install Project
        run: poetry install --no-interaction --no-ansi -vv
      - name: Run All Migrations
        run: poetry run lightning db upgrade